/* automatically generated by rust-bindgen 0.68.1 */

use ctru_sys::*;
use libc::FILE;

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
pub const C2D_DEFAULT_MAX_OBJECTS: u16 = 4096;
pub type __int64_t = ::libc::c_longlong;
pub type _off_t = __int64_t;
pub type _fpos_t = __int64_t;
pub type wint_t = ::libc::c_int;
#[doc = "C3D_FVec\n Float vector\n\n Matches PICA layout"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union C3D_FVec {
    pub __bindgen_anon_1: C3D_FVec__bindgen_ty_1,
    pub __bindgen_anon_2: C3D_FVec__bindgen_ty_2,
    #[doc = "Raw access"]
    pub c: [f32; 4usize],
}
#[doc = "Vector access"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_FVec__bindgen_ty_1 {
    #[doc = "< W-component"]
    pub w: f32,
    #[doc = "< Z-component"]
    pub z: f32,
    #[doc = "< Y-component"]
    pub y: f32,
    #[doc = "< X-component"]
    pub x: f32,
}
#[doc = "Quaternion access"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_FVec__bindgen_ty_2 {
    #[doc = "< Real component"]
    pub r: f32,
    #[doc = "< K-component"]
    pub k: f32,
    #[doc = "< J-component"]
    pub j: f32,
    #[doc = "< I-component"]
    pub i: f32,
}
#[doc = "C3D_Mtx\n Row-major 4x4 matrix"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union C3D_Mtx {
    #[doc = "< Rows are vectors"]
    pub r: [C3D_FVec; 4usize],
    #[doc = "< Raw access"]
    pub m: [f32; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_TexCube {
    pub data: [*mut ::libc::c_void; 6usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct C3D_Tex {
    pub __bindgen_anon_1: C3D_Tex__bindgen_ty_1,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
    pub __bindgen_anon_2: C3D_Tex__bindgen_ty_2,
    pub param: u32_,
    pub border: u32_,
    pub __bindgen_anon_3: C3D_Tex__bindgen_ty_3,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union C3D_Tex__bindgen_ty_1 {
    pub data: *mut ::libc::c_void,
    pub cube: *mut C3D_TexCube,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union C3D_Tex__bindgen_ty_2 {
    pub dim: u32_,
    pub __bindgen_anon_1: C3D_Tex__bindgen_ty_2__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_Tex__bindgen_ty_2__bindgen_ty_1 {
    pub height: u16_,
    pub width: u16_,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union C3D_Tex__bindgen_ty_3 {
    pub lodParam: u32_,
    pub __bindgen_anon_1: C3D_Tex__bindgen_ty_3__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_Tex__bindgen_ty_3__bindgen_ty_1 {
    pub lodBias: u16_,
    pub maxLevel: u8_,
    pub minLevel: u8_,
}
impl C3D_Tex {
    #[inline]
    pub fn fmt(&self) -> GPU_TEXCOLOR {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 4u8) as u8) }
    }
    #[inline]
    pub fn set_fmt(&mut self, val: GPU_TEXCOLOR) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 4u8, val as u64)
        }
    }
    #[inline]
    pub fn size(&self) -> usize {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(4usize, 28u8) as u32) }
    }
    #[inline]
    pub fn set_size(&mut self, val: usize) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(4usize, 28u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(fmt: GPU_TEXCOLOR, size: usize) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 4u8, {
            let fmt: u8 = unsafe { ::core::mem::transmute(fmt) };
            fmt as u64
        });
        __bindgen_bitfield_unit.set(4usize, 28u8, {
            let size: u32 = unsafe { ::core::mem::transmute(size) };
            size as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_FrameBuf {
    pub colorBuf: *mut ::libc::c_void,
    pub depthBuf: *mut ::libc::c_void,
    pub width: u16_,
    pub height: u16_,
    pub colorFmt: GPU_COLORBUF,
    pub depthFmt: GPU_DEPTHBUF,
    pub block32: bool,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
}
impl C3D_FrameBuf {
    #[inline]
    pub fn colorMask(&self) -> u8_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 4u8) as u8) }
    }
    #[inline]
    pub fn set_colorMask(&mut self, val: u8_) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 4u8, val as u64)
        }
    }
    #[inline]
    pub fn depthMask(&self) -> u8_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(4usize, 4u8) as u8) }
    }
    #[inline]
    pub fn set_depthMask(&mut self, val: u8_) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(4usize, 4u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(colorMask: u8_, depthMask: u8_) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 4u8, {
            let colorMask: u8 = unsafe { ::core::mem::transmute(colorMask) };
            colorMask as u64
        });
        __bindgen_bitfield_unit.set(4usize, 4u8, {
            let depthMask: u8 = unsafe { ::core::mem::transmute(depthMask) };
            depthMask as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type C3D_RenderTarget = C3D_RenderTarget_tag;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C3D_RenderTarget_tag {
    pub next: *mut C3D_RenderTarget,
    pub prev: *mut C3D_RenderTarget,
    pub frameBuf: C3D_FrameBuf,
    pub used: bool,
    pub ownsColor: bool,
    pub ownsDepth: bool,
    pub linked: bool,
    pub screen: gfxScreen_t,
    pub side: gfx3dSide_t,
    pub transferFlags: u32_,
}
#[doc = "Subtexture\n > **Note:** If top < bottom, the subtexture is rotated 1/4 revolution counter-clockwise"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Tex3DS_SubTexture {
    #[doc = "< Sub-texture width (pixels)"]
    pub width: u16_,
    #[doc = "< Sub-texture height (pixels)"]
    pub height: u16_,
    #[doc = "< Left u-coordinate"]
    pub left: f32,
    #[doc = "< Top v-coordinate"]
    pub top: f32,
    #[doc = "< Right u-coordinate"]
    pub right: f32,
    #[doc = "< Bottom v-coordinate"]
    pub bottom: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_DrawParams {
    pub pos: C2D_DrawParams__bindgen_ty_1,
    pub center: C2D_DrawParams__bindgen_ty_2,
    pub depth: f32,
    pub angle: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_DrawParams__bindgen_ty_1 {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_DrawParams__bindgen_ty_2 {
    pub x: f32,
    pub y: f32,
}
#[doc = "< Plain solid tint color"]
pub const C2D_TintSolid: C2D_TintMode = 0;
#[doc = "< Tint color multiplied by texture color"]
pub const C2D_TintMult: C2D_TintMode = 1;
#[doc = "< Tint color multiplied by grayscale converted texture color"]
pub const C2D_TintLuma: C2D_TintMode = 2;
pub type C2D_TintMode = ::libc::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_Tint {
    #[doc = "< RGB tint color and Alpha transparency"]
    pub color: u32_,
    #[doc = "< Blending strength of the tint color (0.0~1.0)"]
    pub blend: f32,
}
#[doc = "< Top left corner"]
pub const C2D_TopLeft: C2D_Corner = 0;
#[doc = "< Top right corner"]
pub const C2D_TopRight: C2D_Corner = 1;
#[doc = "< Bottom left corner"]
pub const C2D_BotLeft: C2D_Corner = 2;
#[doc = "< Bottom right corner"]
pub const C2D_BotRight: C2D_Corner = 3;
pub type C2D_Corner = ::libc::c_uchar;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_Image {
    pub tex: *mut C3D_Tex,
    pub subtex: *const Tex3DS_SubTexture,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_ImageTint {
    pub corners: [C2D_Tint; 4usize],
}
extern "C" {
    #[doc = "Clamps a value between bounds\n # Arguments\n\n* `x` (direction in) - The value to clamp\n * `min` (direction in) - The lower bound\n * `max` (direction in) - The upper bound\n # Returns\n\nThe clamped value"]
    #[link_name = "C2D_Clamp__extern"]
    pub fn C2D_Clamp(x: f32, min: f32, max: f32) -> f32;
}
extern "C" {
    #[doc = "Converts a float to u8\n # Arguments\n\n* `x` (direction in) - Input value (0.0~1.0)\n # Returns\n\nOutput value (0~255)"]
    #[link_name = "C2D_FloatToU8__extern"]
    pub fn C2D_FloatToU8(x: f32) -> u8_;
}
extern "C" {
    #[doc = "Builds a 32-bit RGBA color value\n # Arguments\n\n* `r` (direction in) - Red component (0~255)\n * `g` (direction in) - Green component (0~255)\n * `b` (direction in) - Blue component (0~255)\n * `a` (direction in) - Alpha component (0~255)\n # Returns\n\nThe 32-bit RGBA color value"]
    #[link_name = "C2D_Color32__extern"]
    pub fn C2D_Color32(r: u8_, g: u8_, b: u8_, a: u8_) -> u32_;
}
extern "C" {
    #[doc = "Builds a 32-bit RGBA color value from float values\n # Arguments\n\n* `r` (direction in) - Red component (0.0~1.0)\n * `g` (direction in) - Green component (0.0~1.0)\n * `b` (direction in) - Blue component (0.0~1.0)\n * `a` (direction in) - Alpha component (0.0~1.0)\n # Returns\n\nThe 32-bit RGBA color value"]
    #[link_name = "C2D_Color32f__extern"]
    pub fn C2D_Color32f(r: f32, g: f32, b: f32, a: f32) -> u32_;
}
extern "C" {
    #[doc = "Configures one corner of an image tint structure\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `corner` (direction in) - The corner of the image to tint\n * `color` (direction in) - RGB tint color and Alpha transparency\n * `blend` (direction in) - Blending strength of the tint color (0.0~1.0)"]
    #[link_name = "C2D_SetImageTint__extern"]
    pub fn C2D_SetImageTint(tint: *mut C2D_ImageTint, corner: C2D_Corner, color: u32_, blend: f32);
}
extern "C" {
    #[doc = "Configures an image tint structure with the specified tint parameters applied to all corners\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `color` (direction in) - RGB tint color and Alpha transparency\n * `blend` (direction in) - Blending strength of the tint color (0.0~1.0)"]
    #[link_name = "C2D_PlainImageTint__extern"]
    pub fn C2D_PlainImageTint(tint: *mut C2D_ImageTint, color: u32_, blend: f32);
}
extern "C" {
    #[doc = "Configures an image tint structure to just apply transparency to the image\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `alpha` (direction in) - Alpha transparency value to apply to the image"]
    #[link_name = "C2D_AlphaImageTint__extern"]
    pub fn C2D_AlphaImageTint(tint: *mut C2D_ImageTint, alpha: f32);
}
extern "C" {
    #[doc = "Configures an image tint structure with the specified tint parameters applied to the top side (e.g. for gradients)\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `color` (direction in) - RGB tint color and Alpha transparency\n * `blend` (direction in) - Blending strength of the tint color (0.0~1.0)"]
    #[link_name = "C2D_TopImageTint__extern"]
    pub fn C2D_TopImageTint(tint: *mut C2D_ImageTint, color: u32_, blend: f32);
}
extern "C" {
    #[doc = "Configures an image tint structure with the specified tint parameters applied to the bottom side (e.g. for gradients)\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `color` (direction in) - RGB tint color and Alpha transparency\n * `blend` (direction in) - Blending strength of the tint color (0.0~1.0)"]
    #[link_name = "C2D_BottomImageTint__extern"]
    pub fn C2D_BottomImageTint(tint: *mut C2D_ImageTint, color: u32_, blend: f32);
}
extern "C" {
    #[doc = "Configures an image tint structure with the specified tint parameters applied to the left side (e.g. for gradients)\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `color` (direction in) - RGB tint color and Alpha transparency\n * `blend` (direction in) - Blending strength of the tint color (0.0~1.0)"]
    #[link_name = "C2D_LeftImageTint__extern"]
    pub fn C2D_LeftImageTint(tint: *mut C2D_ImageTint, color: u32_, blend: f32);
}
extern "C" {
    #[doc = "Configures an image tint structure with the specified tint parameters applied to the right side (e.g. for gradients)\n # Arguments\n\n* `tint` (direction in) - Image tint structure\n * `color` (direction in) - RGB tint color and Alpha transparency\n * `blend` (direction in) - Blending strength of the tint color (0.0~1.0)"]
    #[link_name = "C2D_RightImageTint__extern"]
    pub fn C2D_RightImageTint(tint: *mut C2D_ImageTint, color: u32_, blend: f32);
}
extern "C" {
    #[doc = "Initialize citro2d\n # Arguments\n\n* `maxObjects` (direction in) - Maximum number of 2D objects that can be drawn per frame.\n > Pass C2D_DEFAULT_MAX_OBJECTS as a starting point.\n # Returns\n\ntrue on success, false on failure"]
    pub fn C2D_Init(maxObjects: usize) -> bool;
}
extern "C" {
    #[doc = "Deinitialize citro2d"]
    pub fn C2D_Fini();
}
extern "C" {
    #[doc = "Prepares the GPU for rendering 2D content\n > This needs to be done only once in the program if citro2d is the sole user of the GPU."]
    pub fn C2D_Prepare();
}
extern "C" {
    #[doc = "Ensures all 2D objects so far have been drawn"]
    pub fn C2D_Flush();
}
extern "C" {
    #[doc = "Configures the size of the 2D scene.\n # Arguments\n\n* `width` (direction in) - The width of the scene, in pixels.\n * `height` (direction in) - The height of the scene, in pixels.\n * `tilt` (direction in) - Whether the scene is tilted like the 3DS's sideways screens."]
    pub fn C2D_SceneSize(width: u32_, height: u32_, tilt: bool);
}
extern "C" {
    #[doc = "Configures the size of the 2D scene to match that of the specified render target.\n # Arguments\n\n* `target` (direction in) - Render target"]
    #[link_name = "C2D_SceneTarget__extern"]
    pub fn C2D_SceneTarget(target: *mut C3D_RenderTarget);
}
extern "C" {
    #[doc = "Resets the model transformation matrix."]
    pub fn C2D_ViewReset();
}
extern "C" {
    #[doc = "Saves the current model transformation matrix.\n # Arguments\n\n* `matrix` (direction out) - Pointer to save the current matrix to"]
    pub fn C2D_ViewSave(matrix: *mut C3D_Mtx);
}
extern "C" {
    #[doc = "Restores a previously saved model transformation matrix.\n # Arguments\n\n* `matrix` (direction in) - Pointer to matrix to restor"]
    pub fn C2D_ViewRestore(matrix: *const C3D_Mtx);
}
extern "C" {
    #[doc = "Translates everything drawn via the model matrix.\n # Arguments\n\n* `x` (direction in) - Translation in the x direction\n * `y` (direction in) - Translation in the y direction"]
    pub fn C2D_ViewTranslate(x: f32, y: f32);
}
extern "C" {
    #[doc = "Rotates everything drawn via the model matrix.\n # Arguments\n\n* `rotation` (direction in) - Rotation in the counterclockwise direction in radians"]
    pub fn C2D_ViewRotate(rotation: f32);
}
extern "C" {
    #[doc = "Rotates everything drawn via the model matrix.\n # Arguments\n\n* `rotation` (direction in) - Rotation in the counterclockwise direction in degrees"]
    #[link_name = "C2D_ViewRotateDegrees__extern"]
    pub fn C2D_ViewRotateDegrees(rotation: f32);
}
extern "C" {
    #[doc = "Shears everything drawn via the model matrix.\n # Arguments\n\n* `x` (direction in) - Shear factor in the x direction\n * `y` (direction in) - Shear factor in the y direction"]
    pub fn C2D_ViewShear(x: f32, y: f32);
}
extern "C" {
    #[doc = "Scales everything drawn via the model matrix.\n # Arguments\n\n* `x` (direction in) - Scale factor in the x direction\n * `y` (direction in) - Scale factor in the y direction"]
    pub fn C2D_ViewScale(x: f32, y: f32);
}
extern "C" {
    #[doc = "Helper function to create a render target for a screen\n # Arguments\n\n* `screen` (direction in) - Screen (GFX_TOP or GFX_BOTTOM)\n * `side` (direction in) - Side (GFX_LEFT or GFX_RIGHT)\n # Returns\n\ncitro3d render target object"]
    pub fn C2D_CreateScreenTarget(screen: gfxScreen_t, side: gfx3dSide_t) -> *mut C3D_RenderTarget;
}
extern "C" {
    #[doc = "Helper function to clear a rendertarget using the specified color\n # Arguments\n\n* `target` (direction in) - Render target to clear\n * `color` (direction in) - 32-bit RGBA color value to fill the target with"]
    pub fn C2D_TargetClear(target: *mut C3D_RenderTarget, color: u32_);
}
extern "C" {
    #[doc = "Helper function to begin drawing a 2D scene on a render target\n # Arguments\n\n* `target` (direction in) - Render target to draw the 2D scene to"]
    #[link_name = "C2D_SceneBegin__extern"]
    pub fn C2D_SceneBegin(target: *mut C3D_RenderTarget);
}
extern "C" {
    #[doc = "Configures the fading color\n # Arguments\n\n* `color` (direction in) - 32-bit RGBA color value to be used as the fading color (0 by default)\n > The alpha component of the color is used as the strength of the fading color.\n If alpha is zero, the fading color has no effect. If it is the highest value,\n the rendered pixels will all have the fading color. Everything inbetween is\n rendered as a blend of the original pixel color and the fading color."]
    pub fn C2D_Fade(color: u32_);
}
extern "C" {
    #[doc = "Configures the formula used to calculate the tinted texture color\n # Arguments\n\n* `mode` (direction in) - Tinting mode\n > Texture tinting works by linearly interpolating between the regular texture color\n and the tinted texture color according to the blending strength parameter.\n This function can be used to change how the tinted texture color is precisely\n calculated, refer to C2D_TintMode for a list of available tinting modes."]
    pub fn C2D_SetTintMode(mode: C2D_TintMode);
}
extern "C" {
    #[doc = "Draws an image using the GPU (variant accepting C2D_DrawParams)\n # Arguments\n\n* `img` (direction in) - Handle of the image to draw\n * `params` (direction in) - Parameters with which to draw the image\n * `tint` (direction in) - Tint parameters to apply to the image (optional, can be null)\n # Returns\n\ntrue on success, false on failure"]
    pub fn C2D_DrawImage(
        img: C2D_Image,
        params: *const C2D_DrawParams,
        tint: *const C2D_ImageTint,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws an image using the GPU (variant accepting position/scaling)\n # Arguments\n\n* `img` (direction in) - Handle of the image to draw\n * `x` (direction in) - X coordinate at which to place the top left corner of the image\n * `y` (direction in) - Y coordinate at which to place the top left corner of the image\n * `depth` (direction in) - Depth value to draw the image with\n * `tint` (direction in) - Tint parameters to apply to the image (optional, can be null)\n * `scaleX` (direction in) - Horizontal scaling factor to apply to the image (optional, by default 1.0f); negative values apply a horizontal flip\n * `scaleY` (direction in) - Vertical scaling factor to apply to the image (optional, by default 1.0f); negative values apply a vertical flip"]
    #[link_name = "C2D_DrawImageAt__extern"]
    pub fn C2D_DrawImageAt(
        img: C2D_Image,
        x: f32,
        y: f32,
        depth: f32,
        tint: *const C2D_ImageTint,
        scaleX: f32,
        scaleY: f32,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws an image using the GPU (variant accepting position/scaling/rotation)\n # Arguments\n\n* `img` (direction in) - Handle of the image to draw\n * `x` (direction in) - X coordinate at which to place the center of the image\n * `y` (direction in) - Y coordinate at which to place the center of the image\n * `depth` (direction in) - Depth value to draw the image with\n * `angle` (direction in) - Angle (in radians) to rotate the image by, counter-clockwise\n * `tint` (direction in) - Tint parameters to apply to the image (optional, can be null)\n * `scaleX` (direction in) - Horizontal scaling factor to apply to the image (optional, by default 1.0f); negative values apply a horizontal flip\n * `scaleY` (direction in) - Vertical scaling factor to apply to the image (optional, by default 1.0f); negative values apply a vertical flip"]
    #[link_name = "C2D_DrawImageAtRotated__extern"]
    pub fn C2D_DrawImageAtRotated(
        img: C2D_Image,
        x: f32,
        y: f32,
        depth: f32,
        angle: f32,
        tint: *const C2D_ImageTint,
        scaleX: f32,
        scaleY: f32,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws a plain triangle using the GPU\n # Arguments\n\n* `x0` (direction in) - X coordinate of the first vertex of the triangle\n * `y0` (direction in) - Y coordinate of the first vertex of the triangle\n * `clr0` (direction in) - 32-bit RGBA color of the first vertex of the triangle\n * `x1` (direction in) - X coordinate of the second vertex of the triangle\n * `y1` (direction in) - Y coordinate of the second vertex of the triangle\n * `clr1` (direction in) - 32-bit RGBA color of the second vertex of the triangle\n * `x2` (direction in) - X coordinate of the third vertex of the triangle\n * `y2` (direction in) - Y coordinate of the third vertex of the triangle\n * `clr2` (direction in) - 32-bit RGBA color of the third vertex of the triangle\n * `depth` (direction in) - Depth value to draw the triangle with"]
    pub fn C2D_DrawTriangle(
        x0: f32,
        y0: f32,
        clr0: u32_,
        x1: f32,
        y1: f32,
        clr1: u32_,
        x2: f32,
        y2: f32,
        clr2: u32_,
        depth: f32,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws a plain line using the GPU\n # Arguments\n\n* `x0` (direction in) - X coordinate of the first vertex of the line\n * `y0` (direction in) - Y coordinate of the first vertex of the line\n * `clr0` (direction in) - 32-bit RGBA color of the first vertex of the line\n * `x1` (direction in) - X coordinate of the second vertex of the line\n * `y1` (direction in) - Y coordinate of the second vertex of the line\n * `clr1` (direction in) - 32-bit RGBA color of the second vertex of the line\n * `thickness` (direction in) - Thickness, in pixels, of the line\n * `depth` (direction in) - Depth value to draw the line with"]
    pub fn C2D_DrawLine(
        x0: f32,
        y0: f32,
        clr0: u32_,
        x1: f32,
        y1: f32,
        clr1: u32_,
        thickness: f32,
        depth: f32,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws a plain rectangle using the GPU\n # Arguments\n\n* `x` (direction in) - X coordinate of the top-left vertex of the rectangle\n * `y` (direction in) - Y coordinate of the top-left vertex of the rectangle\n * `z` (direction in) - Z coordinate (depth value) to draw the rectangle with\n * `w` (direction in) - Width of the rectangle\n * `h` (direction in) - Height of the rectangle\n * `clr0` (direction in) - 32-bit RGBA color of the top-left corner of the rectangle\n * `clr1` (direction in) - 32-bit RGBA color of the top-right corner of the rectangle\n * `clr2` (direction in) - 32-bit RGBA color of the bottom-left corner of the rectangle\n * `clr3` (direction in) - 32-bit RGBA color of the bottom-right corner of the rectangle"]
    pub fn C2D_DrawRectangle(
        x: f32,
        y: f32,
        z: f32,
        w: f32,
        h: f32,
        clr0: u32_,
        clr1: u32_,
        clr2: u32_,
        clr3: u32_,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws a plain rectangle using the GPU (with a solid color)\n # Arguments\n\n* `x` (direction in) - X coordinate of the top-left vertex of the rectangle\n * `y` (direction in) - Y coordinate of the top-left vertex of the rectangle\n * `z` (direction in) - Z coordinate (depth value) to draw the rectangle with\n * `w` (direction in) - Width of the rectangle\n * `h` (direction in) - Height of the rectangle\n * `clr` (direction in) - 32-bit RGBA color of the rectangle"]
    #[link_name = "C2D_DrawRectSolid__extern"]
    pub fn C2D_DrawRectSolid(x: f32, y: f32, z: f32, w: f32, h: f32, clr: u32_) -> bool;
}
extern "C" {
    #[doc = "Draws an ellipse using the GPU\n # Arguments\n\n* `x` (direction in) - X coordinate of the top-left vertex of the ellipse\n * `y` (direction in) - Y coordinate of the top-left vertex of the ellipse\n * `z` (direction in) - Z coordinate (depth value) to draw the ellipse with\n * `w` (direction in) - Width of the ellipse\n * `h` (direction in) - Height of the ellipse\n * `clr0` (direction in) - 32-bit RGBA color of the top-left corner of the ellipse\n * `clr1` (direction in) - 32-bit RGBA color of the top-right corner of the ellipse\n * `clr2` (direction in) - 32-bit RGBA color of the bottom-left corner of the ellipse\n * `clr3` (direction in) - 32-bit RGBA color of the bottom-right corner of the ellipse\n > **Note:** Switching to and from \"circle mode\" internally requires an expensive state change. As such, the recommended usage of this feature is to draw all non-circular objects first, then draw all circular objects."]
    pub fn C2D_DrawEllipse(
        x: f32,
        y: f32,
        z: f32,
        w: f32,
        h: f32,
        clr0: u32_,
        clr1: u32_,
        clr2: u32_,
        clr3: u32_,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws a ellipse using the GPU (with a solid color)\n # Arguments\n\n* `x` (direction in) - X coordinate of the top-left vertex of the ellipse\n * `y` (direction in) - Y coordinate of the top-left vertex of the ellipse\n * `z` (direction in) - Z coordinate (depth value) to draw the ellipse with\n * `w` (direction in) - Width of the ellipse\n * `h` (direction in) - Height of the ellipse\n * `clr` (direction in) - 32-bit RGBA color of the ellipse\n > **Note:** Switching to and from \"circle mode\" internally requires an expensive state change. As such, the recommended usage of this feature is to draw all non-circular objects first, then draw all circular objects."]
    #[link_name = "C2D_DrawEllipseSolid__extern"]
    pub fn C2D_DrawEllipseSolid(x: f32, y: f32, z: f32, w: f32, h: f32, clr: u32_) -> bool;
}
extern "C" {
    #[doc = "Draws a circle (an ellipse with identical width and height) using the GPU\n # Arguments\n\n* `x` (direction in) - X coordinate of the center of the circle\n * `y` (direction in) - Y coordinate of the center of the circle\n * `z` (direction in) - Z coordinate (depth value) to draw the ellipse with\n * `radius` (direction in) - Radius of the circle\n * `clr0` (direction in) - 32-bit RGBA color of the top-left corner of the ellipse\n * `clr1` (direction in) - 32-bit RGBA color of the top-right corner of the ellipse\n * `clr2` (direction in) - 32-bit RGBA color of the bottom-left corner of the ellipse\n * `clr3` (direction in) - 32-bit RGBA color of the bottom-right corner of the ellipse\n > **Note:** Switching to and from \"circle mode\" internally requires an expensive state change. As such, the recommended usage of this feature is to draw all non-circular objects first, then draw all circular objects."]
    #[link_name = "C2D_DrawCircle__extern"]
    pub fn C2D_DrawCircle(
        x: f32,
        y: f32,
        z: f32,
        radius: f32,
        clr0: u32_,
        clr1: u32_,
        clr2: u32_,
        clr3: u32_,
    ) -> bool;
}
extern "C" {
    #[doc = "Draws a circle (an ellipse with identical width and height) using the GPU (with a solid color)\n # Arguments\n\n* `x` (direction in) - X coordinate of the center of the circle\n * `y` (direction in) - Y coordinate of the center of the circle\n * `z` (direction in) - Z coordinate (depth value) to draw the ellipse with\n * `radius` (direction in) - Radius of the circle\n * `clr` (direction in) - 32-bit RGBA color of the ellipse\n > **Note:** Switching to and from \"circle mode\" internally requires an expensive state change. As such, the recommended usage of this feature is to draw all non-circular objects first, then draw all circular objects."]
    #[link_name = "C2D_DrawCircleSolid__extern"]
    pub fn C2D_DrawCircleSolid(x: f32, y: f32, z: f32, radius: f32, clr: u32_) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_SpriteSheet_s {
    _unused: [u8; 0],
}
pub type C2D_SpriteSheet = *mut C2D_SpriteSheet_s;
extern "C" {
    #[doc = "Load a sprite sheet from file\n # Arguments\n\n* `filename` (direction in) - Name of the sprite sheet file (.t3x)\n # Returns\n\nSprite sheet handle\n * `NULL` - Error"]
    pub fn C2D_SpriteSheetLoad(filename: *const ::libc::c_char) -> C2D_SpriteSheet;
}
extern "C" {
    #[doc = "Load a sprite sheet from memory\n # Arguments\n\n* `data` (direction in) - Data to load\n * `size` (direction in) - Size of the data to load\n # Returns\n\nSprite sheet handle\n * `NULL` - Error"]
    pub fn C2D_SpriteSheetLoadFromMem(data: *const ::libc::c_void, size: usize) -> C2D_SpriteSheet;
}
extern "C" {
    #[doc = "Load sprite sheet from file descriptor\n # Arguments\n\n* `fd` (direction in) - File descriptor used to load data\n # Returns\n\nSprite sheet handle\n * `NULL` - Error"]
    pub fn C2D_SpriteSheetFromFD(fd: ::libc::c_int) -> C2D_SpriteSheet;
}
extern "C" {
    #[doc = "Load sprite sheet from stdio file handle\n # Arguments\n\n* `f` (direction in) - File handle used to load data\n # Returns\n\nSprite sheet handle\n * `NULL` - Error"]
    pub fn C2D_SpriteSheetLoadFromHandle(f: *mut FILE) -> C2D_SpriteSheet;
}
extern "C" {
    #[doc = "Free a sprite sheet\n # Arguments\n\n* `sheet` (direction in) - Sprite sheet handle"]
    pub fn C2D_SpriteSheetFree(sheet: C2D_SpriteSheet);
}
extern "C" {
    #[doc = "Retrieves the number of sprites in the specified sprite sheet\n # Arguments\n\n* `sheet` (direction in) - Sprite sheet handle\n # Returns\n\nNumber of sprites"]
    pub fn C2D_SpriteSheetCount(sheet: C2D_SpriteSheet) -> usize;
}
extern "C" {
    #[doc = "Retrieves the specified image from the specified sprite sheet\n # Arguments\n\n* `sheet` (direction in) - Sprite sheet handle\n * `index` (direction in) - Index of the image to retrieve\n # Returns\n\nImage object"]
    pub fn C2D_SpriteSheetGetImage(sheet: C2D_SpriteSheet, index: usize) -> C2D_Image;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_Sprite {
    pub image: C2D_Image,
    pub params: C2D_DrawParams,
}
extern "C" {
    #[doc = "Initializes a sprite from an image\n # Arguments\n\n* `Pointer` (direction in) - to sprite\n * `image` (direction in) - Image to use"]
    #[link_name = "C2D_SpriteFromImage__extern"]
    pub fn C2D_SpriteFromImage(sprite: *mut C2D_Sprite, image: C2D_Image);
}
extern "C" {
    #[doc = "Initializes a sprite from an image stored in a sprite sheet\n # Arguments\n\n* `Pointer` (direction in) - to sprite\n * `sheet` (direction in) - Sprite sheet handle\n * `index` (direction in) - Index of the image inside the sprite sheet"]
    #[link_name = "C2D_SpriteFromSheet__extern"]
    pub fn C2D_SpriteFromSheet(sprite: *mut C2D_Sprite, sheet: C2D_SpriteSheet, index: usize);
}
extern "C" {
    #[doc = "Scale sprite (relative)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `x` (direction in) - X scale (negative values flip the sprite horizontally)\n * `y` (direction in) - Y scale (negative values flip the sprite vertically)"]
    #[link_name = "C2D_SpriteScale__extern"]
    pub fn C2D_SpriteScale(sprite: *mut C2D_Sprite, x: f32, y: f32);
}
extern "C" {
    #[doc = "Rotate sprite (relative)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `radians` (direction in) - Amount to rotate in radians"]
    #[link_name = "C2D_SpriteRotate__extern"]
    pub fn C2D_SpriteRotate(sprite: *mut C2D_Sprite, radians: f32);
}
extern "C" {
    #[doc = "Rotate sprite (relative)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `degrees` (direction in) - Amount to rotate in degrees"]
    #[link_name = "C2D_SpriteRotateDegrees__extern"]
    pub fn C2D_SpriteRotateDegrees(sprite: *mut C2D_Sprite, degrees: f32);
}
extern "C" {
    #[doc = "Move sprite (relative)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `x` (direction in) - X translation\n * `y` (direction in) - Y translation"]
    #[link_name = "C2D_SpriteMove__extern"]
    pub fn C2D_SpriteMove(sprite: *mut C2D_Sprite, x: f32, y: f32);
}
extern "C" {
    #[doc = "Scale sprite (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `x` (direction in) - X scale (negative values flip the sprite horizontally)\n * `y` (direction in) - Y scale (negative values flip the sprite vertically)"]
    #[link_name = "C2D_SpriteSetScale__extern"]
    pub fn C2D_SpriteSetScale(sprite: *mut C2D_Sprite, x: f32, y: f32);
}
extern "C" {
    #[doc = "Rotate sprite (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `radians` (direction in) - Amount to rotate in radians"]
    #[link_name = "C2D_SpriteSetRotation__extern"]
    pub fn C2D_SpriteSetRotation(sprite: *mut C2D_Sprite, radians: f32);
}
extern "C" {
    #[doc = "Rotate sprite (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `degrees` (direction in) - Amount to rotate in degrees"]
    #[link_name = "C2D_SpriteSetRotationDegrees__extern"]
    pub fn C2D_SpriteSetRotationDegrees(sprite: *mut C2D_Sprite, degrees: f32);
}
extern "C" {
    #[doc = "Set the center of a sprite in values independent of the sprite size (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `x` (direction in) - X position of the center (0.0 through 1.0)\n * `y` (direction in) - Y position of the center (0.0 through 1.0)"]
    #[link_name = "C2D_SpriteSetCenter__extern"]
    pub fn C2D_SpriteSetCenter(sprite: *mut C2D_Sprite, x: f32, y: f32);
}
extern "C" {
    #[doc = "Set the center of a sprite in terms of pixels (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `x` (direction in) - X position of the center (in pixels)\n * `y` (direction in) - Y position of the center (in pixels)"]
    #[link_name = "C2D_SpriteSetCenterRaw__extern"]
    pub fn C2D_SpriteSetCenterRaw(sprite: *mut C2D_Sprite, x: f32, y: f32);
}
extern "C" {
    #[doc = "Move sprite (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `x` (direction in) - X position\n * `y` (direction in) - Y position"]
    #[link_name = "C2D_SpriteSetPos__extern"]
    pub fn C2D_SpriteSetPos(sprite: *mut C2D_Sprite, x: f32, y: f32);
}
extern "C" {
    #[doc = "Sets the depth level of a sprite (absolute)\n # Arguments\n\n* `sprite` (direction in) - Pointer to sprite\n * `depth` (direction in) - Depth value"]
    #[link_name = "C2D_SpriteSetDepth__extern"]
    pub fn C2D_SpriteSetDepth(sprite: *mut C2D_Sprite, depth: f32);
}
extern "C" {
    #[doc = "Draw sprite\n # Arguments\n\n* `sprite` (direction in) - Sprite to draw"]
    #[link_name = "C2D_DrawSprite__extern"]
    pub fn C2D_DrawSprite(sprite: *const C2D_Sprite) -> bool;
}
extern "C" {
    #[doc = "Draw sprite with color tinting\n # Arguments\n\n* `sprite` (direction in) - Sprite to draw\n * `tint` (direction in) - Color tinting parameters to apply to the sprite"]
    #[link_name = "C2D_DrawSpriteTinted__extern"]
    pub fn C2D_DrawSpriteTinted(sprite: *const C2D_Sprite, tint: *const C2D_ImageTint) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_Font_s {
    _unused: [u8; 0],
}
pub type C2D_Font = *mut C2D_Font_s;
extern "C" {
    #[doc = "Load a font from a file\n # Arguments\n\n* `filename` (direction in) - Name of the font file (.bcfnt)\n # Returns\n\nFont handle\n * `NULL` - Error"]
    pub fn C2D_FontLoad(filename: *const ::libc::c_char) -> C2D_Font;
}
extern "C" {
    #[doc = "Load a font from memory\n # Arguments\n\n* `data` (direction in) - Data to load\n * `size` (direction in) - Size of the data to load\n # Returns\n\nFont handle\n * `NULL` - Error"]
    pub fn C2D_FontLoadFromMem(data: *const ::libc::c_void, size: usize) -> C2D_Font;
}
extern "C" {
    #[doc = "Load a font from file descriptor\n # Arguments\n\n* `fd` (direction in) - File descriptor used to load data\n # Returns\n\nFont handle\n * `NULL` - Error"]
    pub fn C2D_FontLoadFromFD(fd: ::libc::c_int) -> C2D_Font;
}
extern "C" {
    #[doc = "Load font from stdio file handle\n # Arguments\n\n* `f` (direction in) - File handle used to load data\n # Returns\n\nFont handle\n * `NULL` - Error"]
    pub fn C2D_FontLoadFromHandle(f: *mut FILE) -> C2D_Font;
}
extern "C" {
    #[doc = "Load corresponding font from system archive\n # Arguments\n\n* `region` (direction in) - Region to get font from\n # Returns\n\nFont handle\n * `NULL` - Error\n > JPN, USA, EUR, and AUS all use the same font."]
    pub fn C2D_FontLoadSystem(region: CFG_Region) -> C2D_Font;
}
extern "C" {
    #[doc = "Free a font\n # Arguments\n\n* `font` (direction in) - Font handle"]
    pub fn C2D_FontFree(font: C2D_Font);
}
extern "C" {
    #[doc = "Set a font's texture filter\n # Arguments\n\n* `font` (direction in) - Font handle\n * `magFilter` (direction in) - the magnification filter\n * `minFilter` (direction in) - the minification filter"]
    pub fn C2D_FontSetFilter(
        font: C2D_Font,
        magFilter: GPU_TEXTURE_FILTER_PARAM,
        minFilter: GPU_TEXTURE_FILTER_PARAM,
    );
}
extern "C" {
    #[doc = "Find the glyph index of a codepoint, or returns the default\n # Arguments\n\n* `font` (direction in) - Font to search, or NULL for system font\n * `codepoint` (direction in) - Codepoint to search for\n # Returns\n\nGlyph index\n * `font->cfnt->finf.alterCharIndex` - The codepoint does not exist in the font"]
    pub fn C2D_FontGlyphIndexFromCodePoint(font: C2D_Font, codepoint: u32_) -> ::libc::c_int;
}
extern "C" {
    #[doc = "Get character width info for a given index\n # Arguments\n\n* `font` (direction in) - Font to read from, or NULL for system font\n * `glyphIndex` (direction in) - Index to get the width of\n # Returns\n\nWidth info for glyph"]
    pub fn C2D_FontGetCharWidthInfo(
        font: C2D_Font,
        glyphIndex: ::libc::c_int,
    ) -> *mut charWidthInfo_s;
}
extern "C" {
    #[doc = "Calculate glyph position of given index\n # Arguments\n\n* `font` (direction in) - Font to read from, or NULL for system font\n * `out` (direction out) - Glyph position\n * `glyphIndex` (direction in) - Index to get position of\n * `flags` (direction in) - Misc flags\n * `scaleX` (direction in) - Size to scale in X\n * `scaleY` (direction in) - Size to scale in Y"]
    pub fn C2D_FontCalcGlyphPos(
        font: C2D_Font,
        out: *mut fontGlyphPos_s,
        glyphIndex: ::libc::c_int,
        flags: u32_,
        scaleX: f32,
        scaleY: f32,
    );
}
extern "C" {
    #[doc = "Get the font info structure associated with the font\n # Arguments\n\n* `font` (direction in) - Font to read from, or NULL for the system font\n # Returns\n\nFINF associated with the font"]
    pub fn C2D_FontGetInfo(font: C2D_Font) -> *mut FINF_s;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_TextBuf_s {
    _unused: [u8; 0],
}
pub type C2D_TextBuf = *mut C2D_TextBuf_s;
#[doc = "Text object."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct C2D_Text {
    #[doc = "< Buffer associated with the text."]
    pub buf: C2D_TextBuf,
    #[doc = "< Reserved for internal use."]
    pub begin: usize,
    #[doc = "< Reserved for internal use."]
    pub end: usize,
    #[doc = "< Width of the text in pixels, according to 1x scale metrics."]
    pub width: f32,
    #[doc = "< Number of lines in the text."]
    pub lines: u32_,
    #[doc = "< Number of words in the text."]
    pub words: u32_,
    #[doc = "< Font used to draw the text, or NULL for system font"]
    pub font: C2D_Font,
}
#[doc = "< Matches the Y coordinate with the baseline of the font."]
pub const C2D_AtBaseline: _bindgen_ty_45 = 1;
#[doc = "< Draws text with color. Requires a u32 color value."]
pub const C2D_WithColor: _bindgen_ty_45 = 2;
#[doc = "< Draws text aligned to the left. This is the default."]
pub const C2D_AlignLeft: _bindgen_ty_45 = 0;
#[doc = "< Draws text aligned to the right."]
pub const C2D_AlignRight: _bindgen_ty_45 = 4;
#[doc = "< Draws text centered."]
pub const C2D_AlignCenter: _bindgen_ty_45 = 8;
#[doc = "< Draws text justified. When C2D_WordWrap is not specified, right edge is x + scaleX*text->width. Otherwise, right edge is x + the width specified for those values."]
pub const C2D_AlignJustified: _bindgen_ty_45 = 12;
#[doc = "< Bitmask for alignment values."]
pub const C2D_AlignMask: _bindgen_ty_45 = 12;
#[doc = "< Draws text with wrapping of full words before specified width. Requires a float value, passed after color if C2D_WithColor is specified."]
pub const C2D_WordWrap: _bindgen_ty_45 = 16;
pub type _bindgen_ty_45 = ::libc::c_uchar;
extern "C" {
    #[doc = "Creates a new text buffer.\n # Arguments\n\n* `maxGlyphs` (direction in) - Maximum number of glyphs that can be stored in the buffer.\n # Returns\n\nText buffer handle (or NULL on failure)."]
    pub fn C2D_TextBufNew(maxGlyphs: usize) -> C2D_TextBuf;
}
extern "C" {
    #[doc = "Resizes a text buffer.\n # Arguments\n\n* `buf` (direction in) - Text buffer to resize.\n * `maxGlyphs` (direction in) - Maximum number of glyphs that can be stored in the buffer.\n # Returns\n\nNew text buffer handle (or NULL on failure).\n > If successful, old text buffer handle becomes invalid."]
    pub fn C2D_TextBufResize(buf: C2D_TextBuf, maxGlyphs: usize) -> C2D_TextBuf;
}
extern "C" {
    #[doc = "Deletes a text buffer.\n # Arguments\n\n* `buf` (direction in) - Text buffer handle.\n > This also invalidates all text objects previously created with this buffer."]
    pub fn C2D_TextBufDelete(buf: C2D_TextBuf);
}
extern "C" {
    #[doc = "Clears all stored text in a buffer.\n # Arguments\n\n* `buf` (direction in) - Text buffer handle."]
    pub fn C2D_TextBufClear(buf: C2D_TextBuf);
}
extern "C" {
    #[doc = "Retrieves the number of glyphs stored in a text buffer.\n # Arguments\n\n* `buf` (direction in) - Text buffer handle.\n # Returns\n\nThe number of glyphs."]
    pub fn C2D_TextBufGetNumGlyphs(buf: C2D_TextBuf) -> usize;
}
extern "C" {
    #[doc = "Parses and adds a single line of text to a text buffer.\n # Arguments\n\n* `text` (direction out) - Pointer to text object to store information in.\n * `buf` (direction in) - Text buffer handle.\n * `str` (direction in) - String to parse.\n * `lineNo` (direction in) - Line number assigned to the text (used to calculate vertical position).\n > Whitespace doesn't add any glyphs to the text buffer and is thus \"free\".\n # Returns\n\nOn success, a pointer to the character on which string processing stopped, which\n can be a newline ('indicating that's where the line ended), the null character\n ('indicating the end of the string was reached), or any other character\n (indicating the text buffer is full and no more glyphs can be added).\n On failure, NULL."]
    pub fn C2D_TextParseLine(
        text: *mut C2D_Text,
        buf: C2D_TextBuf,
        str_: *const ::libc::c_char,
        lineNo: u32_,
    ) -> *const ::libc::c_char;
}
extern "C" {
    #[doc = "Parses and adds a single line of text to a text buffer.\n # Arguments\n\n* `text` (direction out) - Pointer to text object to store information in.\n * `font` (direction in) - Font to get glyphs from, or null for system font\n * `buf` (direction in) - Text buffer handle.\n * `str` (direction in) - String to parse.\n * `lineNo` (direction in) - Line number assigned to the text (used to calculate vertical position).\n > Whitespace doesn't add any glyphs to the text buffer and is thus \"free\".\n # Returns\n\nOn success, a pointer to the character on which string processing stopped, which\n can be a newline ('indicating that's where the line ended), the null character\n ('indicating the end of the string was reached), or any other character\n (indicating the text buffer is full and no more glyphs can be added).\n On failure, NULL."]
    pub fn C2D_TextFontParseLine(
        text: *mut C2D_Text,
        font: C2D_Font,
        buf: C2D_TextBuf,
        str_: *const ::libc::c_char,
        lineNo: u32_,
    ) -> *const ::libc::c_char;
}
extern "C" {
    #[doc = "Parses and adds arbitrary text (including newlines) to a text buffer.\n # Arguments\n\n* `text` (direction out) - Pointer to text object to store information in.\n * `buf` (direction in) - Text buffer handle.\n * `str` (direction in) - String to parse.\n > Whitespace doesn't add any glyphs to the text buffer and is thus \"free\".\n # Returns\n\nOn success, a pointer to the character on which string processing stopped, which\n can be the null character ('indicating the end of the string was reached),\n or any other character (indicating the text buffer is full and no more glyphs can be added).\n On failure, NULL."]
    pub fn C2D_TextParse(
        text: *mut C2D_Text,
        buf: C2D_TextBuf,
        str_: *const ::libc::c_char,
    ) -> *const ::libc::c_char;
}
extern "C" {
    #[doc = "Parses and adds arbitrary text (including newlines) to a text buffer.\n # Arguments\n\n* `text` (direction out) - Pointer to text object to store information in.\n * `font` (direction in) - Font to get glyphs from, or null for system font\n * `buf` (direction in) - Text buffer handle.\n * `str` (direction in) - String to parse.\n > Whitespace doesn't add any glyphs to the text buffer and is thus \"free\".\n # Returns\n\nOn success, a pointer to the character on which string processing stopped, which\n can be the null character ('indicating the end of the string was reached),\n or any other character (indicating the text buffer is full and no more glyphs can be added).\n On failure, NULL."]
    pub fn C2D_TextFontParse(
        text: *mut C2D_Text,
        font: C2D_Font,
        buf: C2D_TextBuf,
        str_: *const ::libc::c_char,
    ) -> *const ::libc::c_char;
}
extern "C" {
    #[doc = "Optimizes a text object in order to be drawn more efficiently.\n # Arguments\n\n* `text` (direction in) - Pointer to text object."]
    pub fn C2D_TextOptimize(text: *const C2D_Text);
}
extern "C" {
    #[doc = "Retrieves the total dimensions of a text object.\n # Arguments\n\n* `text` (direction in) - Pointer to text object.\n * `scaleX` (direction in) - Horizontal size of the font. 1.0f corresponds to the native size of the font.\n * `scaleY` (direction in) - Vertical size of the font. 1.0f corresponds to the native size of the font.\n * `outWidth` (direction out) - (optional) Variable in which to store the width of the text.\n * `outHeight` (direction out) - (optional) Variable in which to store the height of the text."]
    pub fn C2D_TextGetDimensions(
        text: *const C2D_Text,
        scaleX: f32,
        scaleY: f32,
        outWidth: *mut f32,
        outHeight: *mut f32,
    );
}
extern "C" {
    #[doc = "Draws text using the GPU.\n # Arguments\n\n* `text` (direction in) - Pointer to text object.\n * `flags` (direction in) - Text drawing flags.\n * `x` (direction in) - Horizontal position to draw the text on.\n * `y` (direction in) - Vertical position to draw the text on. If C2D_AtBaseline is not specified (default), this\n is the top left corner of the block of text; otherwise this is the position of the baseline\n of the first line of text.\n * `z` (direction in) - Depth value of the text. If unsure, pass 0.0f.\n * `scaleX` (direction in) - Horizontal size of the font. 1.0f corresponds to the native size of the font.\n * `scaleY` (direction in) - Vertical size of the font. 1.0f corresponds to the native size of the font.\n > The default 3DS system font has a glyph height of 30px, and the baseline is at 25px."]
    pub fn C2D_DrawText(
        text: *const C2D_Text,
        flags: u32_,
        x: f32,
        y: f32,
        z: f32,
        scaleX: f32,
        scaleY: f32,
        ...
    );
}
